darknet_ros_topic: /darknet_ros/bounding_boxes_cam2
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes_cam2
output_goal_topic: /goal_cam2
point_cloud_topic: /cam2/depth_registered/points
working_frame: cam2_link
mininum_detection_thereshold: 0.025
minimum_probability: 0.35
interested_classes: ["hand"]
